media:
  input: public/img
  output: /img
  categories: [image]
content:
  - name: blog_posts
    label: Blog Posts
    type: collection
    path: src/contents
    filename: "{fields.linkname}.md"
    view:
      fields: [title, date]
      sort: [date, title]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: linkname
        label: Linkname (your-title-shortened-with-hyphen)
        type: string
        pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
        required: true
        description: Directory that will be used in the web (deskreview.com/study/...)
      - name: date
        label: Date (dd-mm-yyyy)
        type: string
        pattern: ^([1-9]|0[1-9]|[12][0-9]|3[01])-([1-9]|0[1-9]|1[0-2])-\d{4}$
        required: true
      - name: tag
        label: Tag
        type: select
        options:
          values: [On-Review, Method Review, Working View, Portfolio Review]
        required: true
        description: Single Relevant Tag for the Blog Post
      - name: author
        label: Author
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: works_portfolio
    label: Works Portfolio
    type: collection
    path: src/data/home/portfolio
    filename: "{fields.clientName}.json"
    view:
      fields: [clientName, projectYear]
      sort: [projectYear, clientName]
    fields:
      - name: clientName
        label: Client Name
        type: string
        required: true
      - name: servicesItems
        label: Services Items
        type: string
        list: true
        required: true
      - name: projectYear
        label: Project Year
        type: string
        pattern: ^\d{4}$
        required: true
        description: In yyyy format
      - name: clientIndustry
        label: Client Industry
        type: string
        required: true
      - name: projectDetail
        label: Project Description / Detail
        type: text
        required: true
      - name: projectImages
        label: Project Images
        type: image
        list: true
