media:
  input: public/img
  output: /deskreview-react/img
  categories: [image]
content:
  - name: blog_posts
    label: Blog Posts
    type: collection
    path: src/contents
    filename: "{fields.linkname}.md"
    view:
      fields: [title, date]
      sort: [date, title]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: linkname
        label: Linkname (your-title-shortened-with-hyphen)
        type: string
        pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
        required: true
      - name: date
        label: Date (dd-mm-yyyy)
        type: string
        pattern: ^([1-9]|0[1-9]|[12][0-9]|3[01])-([1-9]|0[1-9]|1[0-2])-\d{4}$
        required: true
      - name: tag
        label: Tag
        type: select
        options:
          values: [On-Review, Method Review, Working View, Portfolio Review]
        required: true
      - name: author
        label: Author
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: works_portfolio
    label: Works Portfolio
    type: collection
    path: src/data/home/portfolio
    filename: "{fields.filename}.json"
    view:
      fields: [clientName, date]
      sort: [date, clientName]
    fields:
      - name: clientName
        label: Client
        type: string
        required: true
      - name: filename
        label: Filename (lowercase_client_name_with_underscore)
        type: string
        pattern: ^[a-z]+(_[a-z]+)*$
        required: true
      - name: servicesItems
        label: Services
        type: string
        list: true
        required: true
      - name: date
        label: Date
        type: string
        pattern: ^\d{4}$
      - name: industry
        label: Industry
        type: string
        required: true
      - name: detail
        label: Project Description / Detail
        type: string
        required: true
      - name: images
        label: Images
        type: image
        list: true
