media: 
  input: public/img/blog
  output: /deskreview-react/img/blog
content:
  - name: posts
    label: Posts
    type: collection
    path: 'src/contents'
    view:
      fields: [title]
    fields:
      - { name: title, type: string, required: true}
      - { name: description, type: string}
      - { name: date, type: string, required: true}
      - { name: tags, type: string, list: true}
      - { name: category, type: string}
      - { name: author, type: string}
      - { name: body, type: rich-text}