media: 
  input: public/img/blog
  output: /deskreview-react/img/blog
content:
  - name: posts
    label: Posts
    type: collection
    path: 'src/contents'
    view:
      fields: [title, date]
      sort: [date, title]
    fields:
      - { name: title, label: Title, type: string, required: true}
      - { name: date, label: Date (dd-mm-yyyy), type: string, required: true}
      - name: tag 
        label: Tag
        type: select
        options: 
          values: [ On-Review, Method Review, Working View, Portfolio Review ]
        required: true
      - { name: author, label: Author, type: string, required: true}
      - { name: description, label: Description, type: string}
      - { name: body, type: rich-text}