name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check for changes in blog or home images
        id: check-changes
        run: |
          # Check if HEAD^ exists
          if git rev-parse HEAD^ > /dev/null 2>&1; then
            if git diff --name-only HEAD^ HEAD | grep -E '^public/img/(blog|home)/'; then
              echo "changes_detected=true" >> $GITHUB_OUTPUT
            else
              echo "changes_detected=false" >> $GITHUB_OUTPUT
            fi
          else
            # If HEAD^ doesn't exist (e.g., first commit), assume changes are detected
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Convert blog images to WebP
        if: steps.check-changes.outputs.changes_detected == 'true'
        run: node src/utils/convertBlogImagesToWebP.js

      - name: Convert home images to WebP
        if: steps.check-changes.outputs.changes_detected == 'true'
        run: node src/utils/convertHomeImagesToWebP.js

      - name: Commit and push converted images
        if: steps.check-changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Convert images to WebP and optimize [skip ci]"
            git push origin main
          fi

      - name: Build
        if: steps.check-changes.outputs.changes_detected == 'false'
        run: npm run build

      - name: Setup Pages
        if: steps.check-changes.outputs.changes_detected == 'false'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: steps.check-changes.outputs.changes_detected == 'false'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Deploy to GitHub Pages
        if: steps.check-changes.outputs.changes_detected == 'false'
        id: deployment
        uses: actions/deploy-pages@v4
